# Generated by Django 5.2.4 on 2025-07-27 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('measurement_time', models.TimeField(blank=True, null=True)),
                ('systolic', models.IntegerField(blank=True, null=True)),
                ('diastolic', models.IntegerField(blank=True, null=True)),
                ('fasting_glucose', models.FloatField(blank=True, null=True)),
                ('post_meal_glucose', models.FloatField(blank=True, null=True)),
                ('hba1c', models.FloatField(blank=True, null=True)),
                ('cgm_reading', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('medication_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('meal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('meal_time', models.TimeField(blank=True, null=True)),
                ('exercise_details', models.CharField(blank=True, max_length=255, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('alcohol_intake', models.BooleanField(default=False)),
                ('caffeine_intake', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
