# Generated by Django 5.2.4 on 2025-07-28 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='medication_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='pulse_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('diabetes_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('gestational', 'Gestational'), ('none', 'None')], default='none', max_length=20)),
                ('hypertension_stage', models.CharField(choices=[('normal', 'Normal'), ('stage1', 'Stage 1'), ('stage2', 'Stage 2'), ('crisis', 'Hypertensive Crisis')], default='normal', max_length=20)),
                ('target_systolic', models.IntegerField(blank=True, null=True)),
                ('target_diastolic', models.IntegerField(blank=True, null=True)),
                ('target_fasting_glucose', models.FloatField(blank=True, null=True)),
                ('target_post_meal_glucose', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
